services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    volumes:
      # - ./_docker-volumes/data:/data/db     # search in doc
      - mongo-db:/data/db     
    networks:
      - mern-network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: backend

    container_name: backend
    working_dir: /app
    ports:
      - 5000:5000
      - 35729:35729

    restart: always
    volumes:
      - .:/app

    env_file: 
      - .env 

    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb/ngenit
    
    depends_on:
      - mongodb
    
    networks:
      - mern-network


volumes:
  mongo-db: 

networks:
  mern-network: 
